name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # Workaround for the GITHUB_TOKEN to be available during semantic-release (https://github.com/semantic-release/git/issues/196#issuecomment-601310576)

      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build # Generate files for distribution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npx semantic-release