name: Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build # Generate files for distribution
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }} # A Github personal access token (https://semantic-release.gitbook.io/semantic-release/usage/ci-configuration#authentication)
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}